import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'sergeystepanov' at '30.06.16 22:02' with Gradle 2.10
 *
 * @author sergeystepanov, @date 30.06.16 22:02
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
    }
}
